// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SevenOutfit.Infrastructure.Data;

#nullable disable

namespace SevenOutfit.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330180630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SevenOutfit.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("Size");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Color = "Blanco",
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(2138),
                            ImageUrl = "https://placehold.co/400x400/white/black?text=Remera+Bendecida",
                            IsActive = true,
                            Name = "Remera Cristiana Bendecida",
                            Price = 15000m,
                            Size = 2,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Category = 3,
                            Color = "Negro",
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(2150),
                            ImageUrl = "https://placehold.co/400x400/black/white?text=Buzo+Seven",
                            IsActive = true,
                            Name = "Buzo Seven Outfit",
                            Price = 35000m,
                            Size = 3,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Category = 5,
                            Color = "Azul",
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(2152),
                            ImageUrl = "https://placehold.co/400x400/blue/white?text=Gorra+Adventista",
                            IsActive = true,
                            Name = "Gorra Adventista",
                            Price = 8000m,
                            Size = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Color = "Gris",
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(2154),
                            ImageUrl = "https://placehold.co/400x400/gray/white?text=Jogger+Faith",
                            IsActive = true,
                            Name = "Pantalón Jogger Faith",
                            Price = 28000m,
                            Size = 2,
                            Stock = 12
                        },
                        new
                        {
                            Id = 5,
                            Category = 4,
                            Color = "Beige",
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(2156),
                            ImageUrl = "https://placehold.co/400x400/beige/black?text=Sweater+Gracias",
                            IsActive = true,
                            Name = "Suéter Gracias",
                            Price = 42000m,
                            Size = 4,
                            Stock = 8
                        },
                        new
                        {
                            Id = 6,
                            Category = 6,
                            Color = "Negro",
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(2158),
                            ImageUrl = "https://placehold.co/400x400/black/white?text=Campera+Urban",
                            IsActive = true,
                            Name = "Campera Urban Spirit",
                            Price = 55000m,
                            Size = 3,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("SevenOutfit.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 18, 6, 29, 407, DateTimeKind.Utc).AddTicks(605),
                            Email = "admin@sevenoutfit.com",
                            PasswordHash = "$2a$11$PEmDo7Guo.ZH0hmWFaO/CODAecN5G6EAwQ1TlmSwpdUDt3hBThPKi",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
